/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChauffeursRouteImport } from './routes/chauffeurs'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as ChauffeurSlugRouteImport } from './routes/chauffeur.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminChauffeursRouteImport } from './routes/_authenticated/admin.chauffeurs'
import { Route as AuthenticatedAdminCoursesRouteImport } from './routes/_authenticated/admin.courses'
import { Route as AuthenticatedAdminSignalementsRouteImport } from './routes/_authenticated/admin.signalements'
import { Route as AuthenticatedAdminUtilisateursRouteImport } from './routes/_authenticated/admin.utilisateurs'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace.index'
import { Route as AuthenticatedEspaceChauffeursRouteImport } from './routes/_authenticated/espace.chauffeurs'
import { Route as AuthenticatedEspaceDemandesRouteImport } from './routes/_authenticated/espace.demandes'
import { Route as AuthenticatedEspaceParametresRouteImport } from './routes/_authenticated/espace.parametres'
import { Route as AuthenticatedProIndexRouteImport } from './routes/_authenticated/pro.index'
import { Route as AuthenticatedProActiviteRouteImport } from './routes/_authenticated/pro.activite'
import { Route as AuthenticatedProAssistantRouteImport } from './routes/_authenticated/pro.assistant'
import { Route as AuthenticatedProClientsRouteImport } from './routes/_authenticated/pro.clients'
import { Route as AuthenticatedProCoursesRouteImport } from './routes/_authenticated/pro.courses'
import { Route as AuthenticatedProDemandesRouteImport } from './routes/_authenticated/pro.demandes'
import { Route as AuthenticatedProEntrepriseRouteImport } from './routes/_authenticated/pro.entreprise'
import { Route as AuthenticatedProFacturesRouteImport } from './routes/_authenticated/pro.factures'
import { Route as AuthenticatedProParametresRouteImport } from './routes/_authenticated/pro.parametres'
import { Route as AuthenticatedProPlanningRouteImport } from './routes/_authenticated/pro.planning'
import { Route as AuthenticatedProProfilRouteImport } from './routes/_authenticated/pro.profil'
import { Route as AuthenticatedProQrRouteImport } from './routes/_authenticated/pro.qr'
import { Route as AuthenticatedProVehiculeRouteImport } from './routes/_authenticated/pro.vehicule'
import { Route as AuthenticatedProVerificationRouteImport } from './routes/_authenticated/pro.verification'
import { Route as ApiPublicPushRouteImport } from './routes/api/public/push'
import { Route as AuthenticatedEspaceCoursesIndexRouteImport } from './routes/_authenticated/espace.courses.index'
import { Route as AuthenticatedEspaceCoursesRideIdRouteImport } from './routes/_authenticated/espace.courses.$rideId'
import { Route as AuthenticatedEspaceCoursesAnnuleesRouteImport } from './routes/_authenticated/espace.courses.annulees'
import { Route as AuthenticatedEspaceCoursesDemandesRouteImport } from './routes/_authenticated/espace.courses.demandes'
import { Route as AuthenticatedEspaceCoursesTermineesRouteImport } from './routes/_authenticated/espace.courses.terminees'
import { Route as AuthenticatedEspaceSuiviIdRouteImport } from './routes/_authenticated/espace.suivi.$id'
import { Route as AuthenticatedProClientsIndexRouteImport } from './routes/_authenticated/pro.clients.index'
import { Route as AuthenticatedProClientsClientIdRouteImport } from './routes/_authenticated/pro.clients.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursRoute = ChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ChauffeurSlugRoute = ChauffeurSlugRouteImport.update({
  id: '/chauffeur/$slug',
  path: '/chauffeur/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminChauffeursRoute =
  AuthenticatedAdminChauffeursRouteImport.update({
    id: '/chauffeurs',
    path: '/chauffeurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminCoursesRoute =
  AuthenticatedAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSignalementsRoute =
  AuthenticatedAdminSignalementsRouteImport.update({
    id: '/signalements',
    path: '/signalements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUtilisateursRoute =
  AuthenticatedAdminUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceChauffeursRoute =
  AuthenticatedEspaceChauffeursRouteImport.update({
    id: '/chauffeurs',
    path: '/chauffeurs',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceDemandesRoute =
  AuthenticatedEspaceDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceParametresRoute =
  AuthenticatedEspaceParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedProIndexRoute = AuthenticatedProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProActiviteRoute =
  AuthenticatedProActiviteRouteImport.update({
    id: '/activite',
    path: '/activite',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProAssistantRoute =
  AuthenticatedProAssistantRouteImport.update({
    id: '/assistant',
    path: '/assistant',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProClientsRoute = AuthenticatedProClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProCoursesRoute = AuthenticatedProCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProDemandesRoute =
  AuthenticatedProDemandesRouteImport.update({
    id: '/demandes',
    path: '/demandes',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProEntrepriseRoute =
  AuthenticatedProEntrepriseRouteImport.update({
    id: '/entreprise',
    path: '/entreprise',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProFacturesRoute =
  AuthenticatedProFacturesRouteImport.update({
    id: '/factures',
    path: '/factures',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProParametresRoute =
  AuthenticatedProParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProPlanningRoute =
  AuthenticatedProPlanningRouteImport.update({
    id: '/planning',
    path: '/planning',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProProfilRoute = AuthenticatedProProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProQrRoute = AuthenticatedProQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProVehiculeRoute =
  AuthenticatedProVehiculeRouteImport.update({
    id: '/vehicule',
    path: '/vehicule',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProVerificationRoute =
  AuthenticatedProVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const ApiPublicPushRoute = ApiPublicPushRouteImport.update({
  id: '/api/public/push',
  path: '/api/public/push',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedEspaceCoursesIndexRoute =
  AuthenticatedEspaceCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceCoursesRideIdRoute =
  AuthenticatedEspaceCoursesRideIdRouteImport.update({
    id: '/courses/$rideId',
    path: '/courses/$rideId',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceCoursesAnnuleesRoute =
  AuthenticatedEspaceCoursesAnnuleesRouteImport.update({
    id: '/courses/annulees',
    path: '/courses/annulees',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceCoursesDemandesRoute =
  AuthenticatedEspaceCoursesDemandesRouteImport.update({
    id: '/courses/demandes',
    path: '/courses/demandes',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceCoursesTermineesRoute =
  AuthenticatedEspaceCoursesTermineesRouteImport.update({
    id: '/courses/terminees',
    path: '/courses/terminees',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceSuiviIdRoute =
  AuthenticatedEspaceSuiviIdRouteImport.update({
    id: '/suivi/$id',
    path: '/suivi/$id',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedProClientsIndexRoute =
  AuthenticatedProClientsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProClientsRoute,
  } as any)
const AuthenticatedProClientsClientIdRoute =
  AuthenticatedProClientsClientIdRouteImport.update({
    id: '/$clientId',
    path: '/$clientId',
    getParentRoute: () => AuthenticatedProClientsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/pro': typeof AuthenticatedProRouteWithChildren
  '/chauffeur/$slug': typeof ChauffeurSlugRoute
  '/admin/chauffeurs': typeof AuthenticatedAdminChauffeursRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/espace/chauffeurs': typeof AuthenticatedEspaceChauffeursRoute
  '/espace/demandes': typeof AuthenticatedEspaceDemandesRoute
  '/espace/parametres': typeof AuthenticatedEspaceParametresRoute
  '/pro/activite': typeof AuthenticatedProActiviteRoute
  '/pro/assistant': typeof AuthenticatedProAssistantRoute
  '/pro/clients': typeof AuthenticatedProClientsRouteWithChildren
  '/pro/courses': typeof AuthenticatedProCoursesRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/entreprise': typeof AuthenticatedProEntrepriseRoute
  '/pro/factures': typeof AuthenticatedProFacturesRoute
  '/pro/parametres': typeof AuthenticatedProParametresRoute
  '/pro/planning': typeof AuthenticatedProPlanningRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/pro/qr': typeof AuthenticatedProQrRoute
  '/pro/vehicule': typeof AuthenticatedProVehiculeRoute
  '/pro/verification': typeof AuthenticatedProVerificationRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
  '/pro/': typeof AuthenticatedProIndexRoute
  '/espace/courses/$rideId': typeof AuthenticatedEspaceCoursesRideIdRoute
  '/espace/courses/annulees': typeof AuthenticatedEspaceCoursesAnnuleesRoute
  '/espace/courses/demandes': typeof AuthenticatedEspaceCoursesDemandesRoute
  '/espace/courses/terminees': typeof AuthenticatedEspaceCoursesTermineesRoute
  '/espace/suivi/$id': typeof AuthenticatedEspaceSuiviIdRoute
  '/pro/clients/$clientId': typeof AuthenticatedProClientsClientIdRoute
  '/espace/courses/': typeof AuthenticatedEspaceCoursesIndexRoute
  '/pro/clients/': typeof AuthenticatedProClientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/chauffeur/$slug': typeof ChauffeurSlugRoute
  '/admin/chauffeurs': typeof AuthenticatedAdminChauffeursRoute
  '/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/espace/chauffeurs': typeof AuthenticatedEspaceChauffeursRoute
  '/espace/demandes': typeof AuthenticatedEspaceDemandesRoute
  '/espace/parametres': typeof AuthenticatedEspaceParametresRoute
  '/pro/activite': typeof AuthenticatedProActiviteRoute
  '/pro/assistant': typeof AuthenticatedProAssistantRoute
  '/pro/courses': typeof AuthenticatedProCoursesRoute
  '/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/pro/entreprise': typeof AuthenticatedProEntrepriseRoute
  '/pro/factures': typeof AuthenticatedProFacturesRoute
  '/pro/parametres': typeof AuthenticatedProParametresRoute
  '/pro/planning': typeof AuthenticatedProPlanningRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/pro/qr': typeof AuthenticatedProQrRoute
  '/pro/vehicule': typeof AuthenticatedProVehiculeRoute
  '/pro/verification': typeof AuthenticatedProVerificationRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
  '/pro': typeof AuthenticatedProIndexRoute
  '/espace/courses/$rideId': typeof AuthenticatedEspaceCoursesRideIdRoute
  '/espace/courses/annulees': typeof AuthenticatedEspaceCoursesAnnuleesRoute
  '/espace/courses/demandes': typeof AuthenticatedEspaceCoursesDemandesRoute
  '/espace/courses/terminees': typeof AuthenticatedEspaceCoursesTermineesRoute
  '/espace/suivi/$id': typeof AuthenticatedEspaceSuiviIdRoute
  '/pro/clients/$clientId': typeof AuthenticatedProClientsClientIdRoute
  '/espace/courses': typeof AuthenticatedEspaceCoursesIndexRoute
  '/pro/clients': typeof AuthenticatedProClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/_authenticated/pro': typeof AuthenticatedProRouteWithChildren
  '/chauffeur/$slug': typeof ChauffeurSlugRoute
  '/_authenticated/admin/chauffeurs': typeof AuthenticatedAdminChauffeursRoute
  '/_authenticated/admin/courses': typeof AuthenticatedAdminCoursesRoute
  '/_authenticated/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/_authenticated/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursRoute
  '/_authenticated/espace/chauffeurs': typeof AuthenticatedEspaceChauffeursRoute
  '/_authenticated/espace/demandes': typeof AuthenticatedEspaceDemandesRoute
  '/_authenticated/espace/parametres': typeof AuthenticatedEspaceParametresRoute
  '/_authenticated/pro/activite': typeof AuthenticatedProActiviteRoute
  '/_authenticated/pro/assistant': typeof AuthenticatedProAssistantRoute
  '/_authenticated/pro/clients': typeof AuthenticatedProClientsRouteWithChildren
  '/_authenticated/pro/courses': typeof AuthenticatedProCoursesRoute
  '/_authenticated/pro/demandes': typeof AuthenticatedProDemandesRoute
  '/_authenticated/pro/entreprise': typeof AuthenticatedProEntrepriseRoute
  '/_authenticated/pro/factures': typeof AuthenticatedProFacturesRoute
  '/_authenticated/pro/parametres': typeof AuthenticatedProParametresRoute
  '/_authenticated/pro/planning': typeof AuthenticatedProPlanningRoute
  '/_authenticated/pro/profil': typeof AuthenticatedProProfilRoute
  '/_authenticated/pro/qr': typeof AuthenticatedProQrRoute
  '/_authenticated/pro/vehicule': typeof AuthenticatedProVehiculeRoute
  '/_authenticated/pro/verification': typeof AuthenticatedProVerificationRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
  '/_authenticated/pro/': typeof AuthenticatedProIndexRoute
  '/_authenticated/espace/courses/$rideId': typeof AuthenticatedEspaceCoursesRideIdRoute
  '/_authenticated/espace/courses/annulees': typeof AuthenticatedEspaceCoursesAnnuleesRoute
  '/_authenticated/espace/courses/demandes': typeof AuthenticatedEspaceCoursesDemandesRoute
  '/_authenticated/espace/courses/terminees': typeof AuthenticatedEspaceCoursesTermineesRoute
  '/_authenticated/espace/suivi/$id': typeof AuthenticatedEspaceSuiviIdRoute
  '/_authenticated/pro/clients/$clientId': typeof AuthenticatedProClientsClientIdRoute
  '/_authenticated/espace/courses/': typeof AuthenticatedEspaceCoursesIndexRoute
  '/_authenticated/pro/clients/': typeof AuthenticatedProClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/chauffeurs'
    | '/sitemap.xml'
    | '/admin'
    | '/espace'
    | '/pro'
    | '/chauffeur/$slug'
    | '/admin/chauffeurs'
    | '/admin/courses'
    | '/admin/signalements'
    | '/admin/utilisateurs'
    | '/espace/chauffeurs'
    | '/espace/demandes'
    | '/espace/parametres'
    | '/pro/activite'
    | '/pro/assistant'
    | '/pro/clients'
    | '/pro/courses'
    | '/pro/demandes'
    | '/pro/entreprise'
    | '/pro/factures'
    | '/pro/parametres'
    | '/pro/planning'
    | '/pro/profil'
    | '/pro/qr'
    | '/pro/vehicule'
    | '/pro/verification'
    | '/api/public/push'
    | '/admin/'
    | '/espace/'
    | '/pro/'
    | '/espace/courses/$rideId'
    | '/espace/courses/annulees'
    | '/espace/courses/demandes'
    | '/espace/courses/terminees'
    | '/espace/suivi/$id'
    | '/pro/clients/$clientId'
    | '/espace/courses/'
    | '/pro/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/chauffeurs'
    | '/sitemap.xml'
    | '/chauffeur/$slug'
    | '/admin/chauffeurs'
    | '/admin/courses'
    | '/admin/signalements'
    | '/admin/utilisateurs'
    | '/espace/chauffeurs'
    | '/espace/demandes'
    | '/espace/parametres'
    | '/pro/activite'
    | '/pro/assistant'
    | '/pro/courses'
    | '/pro/demandes'
    | '/pro/entreprise'
    | '/pro/factures'
    | '/pro/parametres'
    | '/pro/planning'
    | '/pro/profil'
    | '/pro/qr'
    | '/pro/vehicule'
    | '/pro/verification'
    | '/api/public/push'
    | '/admin'
    | '/espace'
    | '/pro'
    | '/espace/courses/$rideId'
    | '/espace/courses/annulees'
    | '/espace/courses/demandes'
    | '/espace/courses/terminees'
    | '/espace/suivi/$id'
    | '/pro/clients/$clientId'
    | '/espace/courses'
    | '/pro/clients'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/chauffeurs'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/espace'
    | '/_authenticated/pro'
    | '/chauffeur/$slug'
    | '/_authenticated/admin/chauffeurs'
    | '/_authenticated/admin/courses'
    | '/_authenticated/admin/signalements'
    | '/_authenticated/admin/utilisateurs'
    | '/_authenticated/espace/chauffeurs'
    | '/_authenticated/espace/demandes'
    | '/_authenticated/espace/parametres'
    | '/_authenticated/pro/activite'
    | '/_authenticated/pro/assistant'
    | '/_authenticated/pro/clients'
    | '/_authenticated/pro/courses'
    | '/_authenticated/pro/demandes'
    | '/_authenticated/pro/entreprise'
    | '/_authenticated/pro/factures'
    | '/_authenticated/pro/parametres'
    | '/_authenticated/pro/planning'
    | '/_authenticated/pro/profil'
    | '/_authenticated/pro/qr'
    | '/_authenticated/pro/vehicule'
    | '/_authenticated/pro/verification'
    | '/api/public/push'
    | '/_authenticated/admin/'
    | '/_authenticated/espace/'
    | '/_authenticated/pro/'
    | '/_authenticated/espace/courses/$rideId'
    | '/_authenticated/espace/courses/annulees'
    | '/_authenticated/espace/courses/demandes'
    | '/_authenticated/espace/courses/terminees'
    | '/_authenticated/espace/suivi/$id'
    | '/_authenticated/pro/clients/$clientId'
    | '/_authenticated/espace/courses/'
    | '/_authenticated/pro/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChauffeursRoute: typeof ChauffeursRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ChauffeurSlugRoute: typeof ChauffeurSlugRoute
  ApiPublicPushRoute: typeof ApiPublicPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs': {
      id: '/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/chauffeurs'
      preLoaderRoute: typeof ChauffeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/chauffeur/$slug': {
      id: '/chauffeur/$slug'
      path: '/chauffeur/$slug'
      fullPath: '/chauffeur/$slug'
      preLoaderRoute: typeof ChauffeurSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chauffeurs': {
      id: '/_authenticated/admin/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/admin/chauffeurs'
      preLoaderRoute: typeof AuthenticatedAdminChauffeursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/courses': {
      id: '/_authenticated/admin/courses'
      path: '/courses'
      fullPath: '/admin/courses'
      preLoaderRoute: typeof AuthenticatedAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/signalements': {
      id: '/_authenticated/admin/signalements'
      path: '/signalements'
      fullPath: '/admin/signalements'
      preLoaderRoute: typeof AuthenticatedAdminSignalementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs': {
      id: '/_authenticated/admin/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/chauffeurs': {
      id: '/_authenticated/espace/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/espace/chauffeurs'
      preLoaderRoute: typeof AuthenticatedEspaceChauffeursRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/demandes': {
      id: '/_authenticated/espace/demandes'
      path: '/demandes'
      fullPath: '/espace/demandes'
      preLoaderRoute: typeof AuthenticatedEspaceDemandesRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/parametres': {
      id: '/_authenticated/espace/parametres'
      path: '/parametres'
      fullPath: '/espace/parametres'
      preLoaderRoute: typeof AuthenticatedEspaceParametresRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/pro/': {
      id: '/_authenticated/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof AuthenticatedProIndexRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/activite': {
      id: '/_authenticated/pro/activite'
      path: '/activite'
      fullPath: '/pro/activite'
      preLoaderRoute: typeof AuthenticatedProActiviteRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/assistant': {
      id: '/_authenticated/pro/assistant'
      path: '/assistant'
      fullPath: '/pro/assistant'
      preLoaderRoute: typeof AuthenticatedProAssistantRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/clients': {
      id: '/_authenticated/pro/clients'
      path: '/clients'
      fullPath: '/pro/clients'
      preLoaderRoute: typeof AuthenticatedProClientsRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/courses': {
      id: '/_authenticated/pro/courses'
      path: '/courses'
      fullPath: '/pro/courses'
      preLoaderRoute: typeof AuthenticatedProCoursesRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/demandes': {
      id: '/_authenticated/pro/demandes'
      path: '/demandes'
      fullPath: '/pro/demandes'
      preLoaderRoute: typeof AuthenticatedProDemandesRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/entreprise': {
      id: '/_authenticated/pro/entreprise'
      path: '/entreprise'
      fullPath: '/pro/entreprise'
      preLoaderRoute: typeof AuthenticatedProEntrepriseRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/factures': {
      id: '/_authenticated/pro/factures'
      path: '/factures'
      fullPath: '/pro/factures'
      preLoaderRoute: typeof AuthenticatedProFacturesRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/parametres': {
      id: '/_authenticated/pro/parametres'
      path: '/parametres'
      fullPath: '/pro/parametres'
      preLoaderRoute: typeof AuthenticatedProParametresRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/planning': {
      id: '/_authenticated/pro/planning'
      path: '/planning'
      fullPath: '/pro/planning'
      preLoaderRoute: typeof AuthenticatedProPlanningRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/profil': {
      id: '/_authenticated/pro/profil'
      path: '/profil'
      fullPath: '/pro/profil'
      preLoaderRoute: typeof AuthenticatedProProfilRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/qr': {
      id: '/_authenticated/pro/qr'
      path: '/qr'
      fullPath: '/pro/qr'
      preLoaderRoute: typeof AuthenticatedProQrRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/vehicule': {
      id: '/_authenticated/pro/vehicule'
      path: '/vehicule'
      fullPath: '/pro/vehicule'
      preLoaderRoute: typeof AuthenticatedProVehiculeRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/verification': {
      id: '/_authenticated/pro/verification'
      path: '/verification'
      fullPath: '/pro/verification'
      preLoaderRoute: typeof AuthenticatedProVerificationRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/api/public/push': {
      id: '/api/public/push'
      path: '/api/public/push'
      fullPath: '/api/public/push'
      preLoaderRoute: typeof ApiPublicPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/espace/courses/': {
      id: '/_authenticated/espace/courses/'
      path: '/courses'
      fullPath: '/espace/courses/'
      preLoaderRoute: typeof AuthenticatedEspaceCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/courses/$rideId': {
      id: '/_authenticated/espace/courses/$rideId'
      path: '/courses/$rideId'
      fullPath: '/espace/courses/$rideId'
      preLoaderRoute: typeof AuthenticatedEspaceCoursesRideIdRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/courses/annulees': {
      id: '/_authenticated/espace/courses/annulees'
      path: '/courses/annulees'
      fullPath: '/espace/courses/annulees'
      preLoaderRoute: typeof AuthenticatedEspaceCoursesAnnuleesRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/courses/demandes': {
      id: '/_authenticated/espace/courses/demandes'
      path: '/courses/demandes'
      fullPath: '/espace/courses/demandes'
      preLoaderRoute: typeof AuthenticatedEspaceCoursesDemandesRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/courses/terminees': {
      id: '/_authenticated/espace/courses/terminees'
      path: '/courses/terminees'
      fullPath: '/espace/courses/terminees'
      preLoaderRoute: typeof AuthenticatedEspaceCoursesTermineesRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/suivi/$id': {
      id: '/_authenticated/espace/suivi/$id'
      path: '/suivi/$id'
      fullPath: '/espace/suivi/$id'
      preLoaderRoute: typeof AuthenticatedEspaceSuiviIdRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/pro/clients/': {
      id: '/_authenticated/pro/clients/'
      path: '/'
      fullPath: '/pro/clients/'
      preLoaderRoute: typeof AuthenticatedProClientsIndexRouteImport
      parentRoute: typeof AuthenticatedProClientsRoute
    }
    '/_authenticated/pro/clients/$clientId': {
      id: '/_authenticated/pro/clients/$clientId'
      path: '/$clientId'
      fullPath: '/pro/clients/$clientId'
      preLoaderRoute: typeof AuthenticatedProClientsClientIdRouteImport
      parentRoute: typeof AuthenticatedProClientsRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminChauffeursRoute: typeof AuthenticatedAdminChauffeursRoute
  AuthenticatedAdminCoursesRoute: typeof AuthenticatedAdminCoursesRoute
  AuthenticatedAdminSignalementsRoute: typeof AuthenticatedAdminSignalementsRoute
  AuthenticatedAdminUtilisateursRoute: typeof AuthenticatedAdminUtilisateursRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminChauffeursRoute: AuthenticatedAdminChauffeursRoute,
  AuthenticatedAdminCoursesRoute: AuthenticatedAdminCoursesRoute,
  AuthenticatedAdminSignalementsRoute: AuthenticatedAdminSignalementsRoute,
  AuthenticatedAdminUtilisateursRoute: AuthenticatedAdminUtilisateursRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEspaceRouteChildren {
  AuthenticatedEspaceChauffeursRoute: typeof AuthenticatedEspaceChauffeursRoute
  AuthenticatedEspaceDemandesRoute: typeof AuthenticatedEspaceDemandesRoute
  AuthenticatedEspaceParametresRoute: typeof AuthenticatedEspaceParametresRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
  AuthenticatedEspaceCoursesRideIdRoute: typeof AuthenticatedEspaceCoursesRideIdRoute
  AuthenticatedEspaceCoursesAnnuleesRoute: typeof AuthenticatedEspaceCoursesAnnuleesRoute
  AuthenticatedEspaceCoursesDemandesRoute: typeof AuthenticatedEspaceCoursesDemandesRoute
  AuthenticatedEspaceCoursesTermineesRoute: typeof AuthenticatedEspaceCoursesTermineesRoute
  AuthenticatedEspaceSuiviIdRoute: typeof AuthenticatedEspaceSuiviIdRoute
  AuthenticatedEspaceCoursesIndexRoute: typeof AuthenticatedEspaceCoursesIndexRoute
}

const AuthenticatedEspaceRouteChildren: AuthenticatedEspaceRouteChildren = {
  AuthenticatedEspaceChauffeursRoute: AuthenticatedEspaceChauffeursRoute,
  AuthenticatedEspaceDemandesRoute: AuthenticatedEspaceDemandesRoute,
  AuthenticatedEspaceParametresRoute: AuthenticatedEspaceParametresRoute,
  AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
  AuthenticatedEspaceCoursesRideIdRoute: AuthenticatedEspaceCoursesRideIdRoute,
  AuthenticatedEspaceCoursesAnnuleesRoute:
    AuthenticatedEspaceCoursesAnnuleesRoute,
  AuthenticatedEspaceCoursesDemandesRoute:
    AuthenticatedEspaceCoursesDemandesRoute,
  AuthenticatedEspaceCoursesTermineesRoute:
    AuthenticatedEspaceCoursesTermineesRoute,
  AuthenticatedEspaceSuiviIdRoute: AuthenticatedEspaceSuiviIdRoute,
  AuthenticatedEspaceCoursesIndexRoute: AuthenticatedEspaceCoursesIndexRoute,
}

const AuthenticatedEspaceRouteWithChildren =
  AuthenticatedEspaceRoute._addFileChildren(AuthenticatedEspaceRouteChildren)

interface AuthenticatedProClientsRouteChildren {
  AuthenticatedProClientsClientIdRoute: typeof AuthenticatedProClientsClientIdRoute
  AuthenticatedProClientsIndexRoute: typeof AuthenticatedProClientsIndexRoute
}

const AuthenticatedProClientsRouteChildren: AuthenticatedProClientsRouteChildren =
  {
    AuthenticatedProClientsClientIdRoute: AuthenticatedProClientsClientIdRoute,
    AuthenticatedProClientsIndexRoute: AuthenticatedProClientsIndexRoute,
  }

const AuthenticatedProClientsRouteWithChildren =
  AuthenticatedProClientsRoute._addFileChildren(
    AuthenticatedProClientsRouteChildren,
  )

interface AuthenticatedProRouteChildren {
  AuthenticatedProActiviteRoute: typeof AuthenticatedProActiviteRoute
  AuthenticatedProAssistantRoute: typeof AuthenticatedProAssistantRoute
  AuthenticatedProClientsRoute: typeof AuthenticatedProClientsRouteWithChildren
  AuthenticatedProCoursesRoute: typeof AuthenticatedProCoursesRoute
  AuthenticatedProDemandesRoute: typeof AuthenticatedProDemandesRoute
  AuthenticatedProEntrepriseRoute: typeof AuthenticatedProEntrepriseRoute
  AuthenticatedProFacturesRoute: typeof AuthenticatedProFacturesRoute
  AuthenticatedProParametresRoute: typeof AuthenticatedProParametresRoute
  AuthenticatedProPlanningRoute: typeof AuthenticatedProPlanningRoute
  AuthenticatedProProfilRoute: typeof AuthenticatedProProfilRoute
  AuthenticatedProQrRoute: typeof AuthenticatedProQrRoute
  AuthenticatedProVehiculeRoute: typeof AuthenticatedProVehiculeRoute
  AuthenticatedProVerificationRoute: typeof AuthenticatedProVerificationRoute
  AuthenticatedProIndexRoute: typeof AuthenticatedProIndexRoute
}

const AuthenticatedProRouteChildren: AuthenticatedProRouteChildren = {
  AuthenticatedProActiviteRoute: AuthenticatedProActiviteRoute,
  AuthenticatedProAssistantRoute: AuthenticatedProAssistantRoute,
  AuthenticatedProClientsRoute: AuthenticatedProClientsRouteWithChildren,
  AuthenticatedProCoursesRoute: AuthenticatedProCoursesRoute,
  AuthenticatedProDemandesRoute: AuthenticatedProDemandesRoute,
  AuthenticatedProEntrepriseRoute: AuthenticatedProEntrepriseRoute,
  AuthenticatedProFacturesRoute: AuthenticatedProFacturesRoute,
  AuthenticatedProParametresRoute: AuthenticatedProParametresRoute,
  AuthenticatedProPlanningRoute: AuthenticatedProPlanningRoute,
  AuthenticatedProProfilRoute: AuthenticatedProProfilRoute,
  AuthenticatedProQrRoute: AuthenticatedProQrRoute,
  AuthenticatedProVehiculeRoute: AuthenticatedProVehiculeRoute,
  AuthenticatedProVerificationRoute: AuthenticatedProVerificationRoute,
  AuthenticatedProIndexRoute: AuthenticatedProIndexRoute,
}

const AuthenticatedProRouteWithChildren =
  AuthenticatedProRoute._addFileChildren(AuthenticatedProRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRouteWithChildren
  AuthenticatedProRoute: typeof AuthenticatedProRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedEspaceRoute: AuthenticatedEspaceRouteWithChildren,
  AuthenticatedProRoute: AuthenticatedProRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ChauffeursRoute: ChauffeursRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ChauffeurSlugRoute: ChauffeurSlugRoute,
  ApiPublicPushRoute: ApiPublicPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
