/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ChauffeursRouteImport } from './routes/chauffeurs'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VerificationRouteImport } from './routes/verification'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedEspaceRouteImport } from './routes/_authenticated/espace'
import { Route as AuthenticatedProRouteImport } from './routes/_authenticated/pro'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as AuthConfirmRouteImport } from './routes/auth_.confirm'
import { Route as ChauffeurSlugRouteImport } from './routes/chauffeur.$slug'
import { Route as LegalDocRouteImport } from './routes/legal.$doc'
import { Route as QSlugRouteImport } from './routes/q.$slug'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedAdminInscriptionsRouteImport } from './routes/_authenticated/admin.inscriptions'
import { Route as AuthenticatedAdminSignalementsRouteImport } from './routes/_authenticated/admin.signalements'
import { Route as AuthenticatedAdminTop10RouteImport } from './routes/_authenticated/admin.top10'
import { Route as AuthenticatedEspaceIndexRouteImport } from './routes/_authenticated/espace.index'
import { Route as AuthenticatedEspaceChauffeursRouteImport } from './routes/_authenticated/espace.chauffeurs'
import { Route as AuthenticatedEspaceDecouvrirRouteImport } from './routes/_authenticated/espace.decouvrir'
import { Route as AuthenticatedEspaceParametresRouteImport } from './routes/_authenticated/espace.parametres'
import { Route as AuthenticatedEspaceScannerRouteImport } from './routes/_authenticated/espace.scanner'
import { Route as AuthenticatedProIndexRouteImport } from './routes/_authenticated/pro.index'
import { Route as AuthenticatedProDossierRouteImport } from './routes/_authenticated/pro.dossier'
import { Route as AuthenticatedProEntrepriseRouteImport } from './routes/_authenticated/pro.entreprise'
import { Route as AuthenticatedProLiensRouteImport } from './routes/_authenticated/pro.liens'
import { Route as AuthenticatedProParametresRouteImport } from './routes/_authenticated/pro.parametres'
import { Route as AuthenticatedProPersonnalisationRouteImport } from './routes/_authenticated/pro.personnalisation'
import { Route as AuthenticatedProProfilRouteImport } from './routes/_authenticated/pro.profil'
import { Route as AuthenticatedProQrRouteImport } from './routes/_authenticated/pro.qr'
import { Route as AuthenticatedProTarificationRouteImport } from './routes/_authenticated/pro.tarification'
import { Route as AuthenticatedProVehiculeRouteImport } from './routes/_authenticated/pro.vehicule'
import { Route as AuthenticatedProVerificationRouteImport } from './routes/_authenticated/pro.verification'
import { Route as AuthenticatedSupportIndexRouteImport } from './routes/_authenticated/support.index'
import { Route as AuthenticatedSupportTicketIdRouteImport } from './routes/_authenticated/support.$ticketId'
import { Route as AuthenticatedSupportNouveauRouteImport } from './routes/_authenticated/support.nouveau'
import { Route as ApiPublicPushRouteImport } from './routes/api/public/push'
import { Route as AuthenticatedAdminChauffeursIndexRouteImport } from './routes/_authenticated/admin.chauffeurs.index'
import { Route as AuthenticatedAdminChauffeursDriverIdRouteImport } from './routes/_authenticated/admin.chauffeurs.$driverId'
import { Route as AuthenticatedAdminInscriptionsIndexRouteImport } from './routes/_authenticated/admin.inscriptions.index'
import { Route as AuthenticatedAdminInscriptionsDriverIdRouteImport } from './routes/_authenticated/admin.inscriptions.$driverId'
import { Route as AuthenticatedAdminSupportIndexRouteImport } from './routes/_authenticated/admin.support.index'
import { Route as AuthenticatedAdminSupportTicketIdRouteImport } from './routes/_authenticated/admin.support.$ticketId'
import { Route as AuthenticatedAdminUtilisateursIndexRouteImport } from './routes/_authenticated/admin.utilisateurs.index'
import { Route as AuthenticatedAdminUtilisateursClientIdRouteImport } from './routes/_authenticated/admin.utilisateurs.$clientId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeursRoute = ChauffeursRouteImport.update({
  id: '/chauffeurs',
  path: '/chauffeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VerificationRoute = VerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEspaceRoute = AuthenticatedEspaceRouteImport.update({
  id: '/espace',
  path: '/espace',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProRoute = AuthenticatedProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth_/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ChauffeurSlugRoute = ChauffeurSlugRouteImport.update({
  id: '/chauffeur/$slug',
  path: '/chauffeur/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalDocRoute = LegalDocRouteImport.update({
  id: '/legal/$doc',
  path: '/legal/$doc',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminInscriptionsRoute =
  AuthenticatedAdminInscriptionsRouteImport.update({
    id: '/inscriptions',
    path: '/inscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSignalementsRoute =
  AuthenticatedAdminSignalementsRouteImport.update({
    id: '/signalements',
    path: '/signalements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTop10Route = AuthenticatedAdminTop10RouteImport.update({
  id: '/top10',
  path: '/top10',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedEspaceIndexRoute =
  AuthenticatedEspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceChauffeursRoute =
  AuthenticatedEspaceChauffeursRouteImport.update({
    id: '/chauffeurs',
    path: '/chauffeurs',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceDecouvrirRoute =
  AuthenticatedEspaceDecouvrirRouteImport.update({
    id: '/decouvrir',
    path: '/decouvrir',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceParametresRoute =
  AuthenticatedEspaceParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedEspaceScannerRoute =
  AuthenticatedEspaceScannerRouteImport.update({
    id: '/scanner',
    path: '/scanner',
    getParentRoute: () => AuthenticatedEspaceRoute,
  } as any)
const AuthenticatedProIndexRoute = AuthenticatedProIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProDossierRoute = AuthenticatedProDossierRouteImport.update({
  id: '/dossier',
  path: '/dossier',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProEntrepriseRoute =
  AuthenticatedProEntrepriseRouteImport.update({
    id: '/entreprise',
    path: '/entreprise',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProLiensRoute = AuthenticatedProLiensRouteImport.update({
  id: '/liens',
  path: '/liens',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProParametresRoute =
  AuthenticatedProParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProPersonnalisationRoute =
  AuthenticatedProPersonnalisationRouteImport.update({
    id: '/personnalisation',
    path: '/personnalisation',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProProfilRoute = AuthenticatedProProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProQrRoute = AuthenticatedProQrRouteImport.update({
  id: '/qr',
  path: '/qr',
  getParentRoute: () => AuthenticatedProRoute,
} as any)
const AuthenticatedProTarificationRoute =
  AuthenticatedProTarificationRouteImport.update({
    id: '/tarification',
    path: '/tarification',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProVehiculeRoute =
  AuthenticatedProVehiculeRouteImport.update({
    id: '/vehicule',
    path: '/vehicule',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedProVerificationRoute =
  AuthenticatedProVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => AuthenticatedProRoute,
  } as any)
const AuthenticatedSupportIndexRoute =
  AuthenticatedSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportTicketIdRoute =
  AuthenticatedSupportTicketIdRouteImport.update({
    id: '/support/$ticketId',
    path: '/support/$ticketId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupportNouveauRoute =
  AuthenticatedSupportNouveauRouteImport.update({
    id: '/support/nouveau',
    path: '/support/nouveau',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicPushRoute = ApiPublicPushRouteImport.update({
  id: '/api/public/push',
  path: '/api/public/push',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminChauffeursIndexRoute =
  AuthenticatedAdminChauffeursIndexRouteImport.update({
    id: '/chauffeurs/',
    path: '/chauffeurs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminChauffeursDriverIdRoute =
  AuthenticatedAdminChauffeursDriverIdRouteImport.update({
    id: '/chauffeurs/$driverId',
    path: '/chauffeurs/$driverId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInscriptionsIndexRoute =
  AuthenticatedAdminInscriptionsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAdminInscriptionsRoute,
  } as any)
const AuthenticatedAdminInscriptionsDriverIdRoute =
  AuthenticatedAdminInscriptionsDriverIdRouteImport.update({
    id: '/$driverId',
    path: '/$driverId',
    getParentRoute: () => AuthenticatedAdminInscriptionsRoute,
  } as any)
const AuthenticatedAdminSupportIndexRoute =
  AuthenticatedAdminSupportIndexRouteImport.update({
    id: '/support/',
    path: '/support/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportTicketIdRoute =
  AuthenticatedAdminSupportTicketIdRouteImport.update({
    id: '/support/$ticketId',
    path: '/support/$ticketId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUtilisateursIndexRoute =
  AuthenticatedAdminUtilisateursIndexRouteImport.update({
    id: '/utilisateurs/',
    path: '/utilisateurs/',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminUtilisateursClientIdRoute =
  AuthenticatedAdminUtilisateursClientIdRouteImport.update({
    id: '/utilisateurs/$clientId',
    path: '/utilisateurs/$clientId',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/pro': typeof AuthenticatedProRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/chauffeur/$slug': typeof ChauffeurSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/q/$slug': typeof QSlugRoute
  '/admin/inscriptions': typeof AuthenticatedAdminInscriptionsRouteWithChildren
  '/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/admin/top10': typeof AuthenticatedAdminTop10Route
  '/espace/chauffeurs': typeof AuthenticatedEspaceChauffeursRoute
  '/espace/decouvrir': typeof AuthenticatedEspaceDecouvrirRoute
  '/espace/parametres': typeof AuthenticatedEspaceParametresRoute
  '/espace/scanner': typeof AuthenticatedEspaceScannerRoute
  '/pro/dossier': typeof AuthenticatedProDossierRoute
  '/pro/entreprise': typeof AuthenticatedProEntrepriseRoute
  '/pro/liens': typeof AuthenticatedProLiensRoute
  '/pro/parametres': typeof AuthenticatedProParametresRoute
  '/pro/personnalisation': typeof AuthenticatedProPersonnalisationRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/pro/qr': typeof AuthenticatedProQrRoute
  '/pro/tarification': typeof AuthenticatedProTarificationRoute
  '/pro/vehicule': typeof AuthenticatedProVehiculeRoute
  '/pro/verification': typeof AuthenticatedProVerificationRoute
  '/support/$ticketId': typeof AuthenticatedSupportTicketIdRoute
  '/support/nouveau': typeof AuthenticatedSupportNouveauRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/espace/': typeof AuthenticatedEspaceIndexRoute
  '/pro/': typeof AuthenticatedProIndexRoute
  '/support/': typeof AuthenticatedSupportIndexRoute
  '/admin/chauffeurs/$driverId': typeof AuthenticatedAdminChauffeursDriverIdRoute
  '/admin/inscriptions/$driverId': typeof AuthenticatedAdminInscriptionsDriverIdRoute
  '/admin/support/$ticketId': typeof AuthenticatedAdminSupportTicketIdRoute
  '/admin/utilisateurs/$clientId': typeof AuthenticatedAdminUtilisateursClientIdRoute
  '/admin/chauffeurs/': typeof AuthenticatedAdminChauffeursIndexRoute
  '/admin/inscriptions/': typeof AuthenticatedAdminInscriptionsIndexRoute
  '/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/admin/utilisateurs/': typeof AuthenticatedAdminUtilisateursIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/chauffeur/$slug': typeof ChauffeurSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/q/$slug': typeof QSlugRoute
  '/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/admin/top10': typeof AuthenticatedAdminTop10Route
  '/espace/chauffeurs': typeof AuthenticatedEspaceChauffeursRoute
  '/espace/decouvrir': typeof AuthenticatedEspaceDecouvrirRoute
  '/espace/parametres': typeof AuthenticatedEspaceParametresRoute
  '/espace/scanner': typeof AuthenticatedEspaceScannerRoute
  '/pro/dossier': typeof AuthenticatedProDossierRoute
  '/pro/entreprise': typeof AuthenticatedProEntrepriseRoute
  '/pro/liens': typeof AuthenticatedProLiensRoute
  '/pro/parametres': typeof AuthenticatedProParametresRoute
  '/pro/personnalisation': typeof AuthenticatedProPersonnalisationRoute
  '/pro/profil': typeof AuthenticatedProProfilRoute
  '/pro/qr': typeof AuthenticatedProQrRoute
  '/pro/tarification': typeof AuthenticatedProTarificationRoute
  '/pro/vehicule': typeof AuthenticatedProVehiculeRoute
  '/pro/verification': typeof AuthenticatedProVerificationRoute
  '/support/$ticketId': typeof AuthenticatedSupportTicketIdRoute
  '/support/nouveau': typeof AuthenticatedSupportNouveauRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/espace': typeof AuthenticatedEspaceIndexRoute
  '/pro': typeof AuthenticatedProIndexRoute
  '/support': typeof AuthenticatedSupportIndexRoute
  '/admin/chauffeurs/$driverId': typeof AuthenticatedAdminChauffeursDriverIdRoute
  '/admin/inscriptions/$driverId': typeof AuthenticatedAdminInscriptionsDriverIdRoute
  '/admin/support/$ticketId': typeof AuthenticatedAdminSupportTicketIdRoute
  '/admin/utilisateurs/$clientId': typeof AuthenticatedAdminUtilisateursClientIdRoute
  '/admin/chauffeurs': typeof AuthenticatedAdminChauffeursIndexRoute
  '/admin/inscriptions': typeof AuthenticatedAdminInscriptionsIndexRoute
  '/admin/support': typeof AuthenticatedAdminSupportIndexRoute
  '/admin/utilisateurs': typeof AuthenticatedAdminUtilisateursIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/aide': typeof AideRoute
  '/auth': typeof AuthRoute
  '/chauffeurs': typeof ChauffeursRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/verification': typeof VerificationRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/espace': typeof AuthenticatedEspaceRouteWithChildren
  '/_authenticated/pro': typeof AuthenticatedProRouteWithChildren
  '/auth_/callback': typeof AuthCallbackRoute
  '/auth_/confirm': typeof AuthConfirmRoute
  '/chauffeur/$slug': typeof ChauffeurSlugRoute
  '/legal/$doc': typeof LegalDocRoute
  '/q/$slug': typeof QSlugRoute
  '/_authenticated/admin/inscriptions': typeof AuthenticatedAdminInscriptionsRouteWithChildren
  '/_authenticated/admin/signalements': typeof AuthenticatedAdminSignalementsRoute
  '/_authenticated/admin/top10': typeof AuthenticatedAdminTop10Route
  '/_authenticated/espace/chauffeurs': typeof AuthenticatedEspaceChauffeursRoute
  '/_authenticated/espace/decouvrir': typeof AuthenticatedEspaceDecouvrirRoute
  '/_authenticated/espace/parametres': typeof AuthenticatedEspaceParametresRoute
  '/_authenticated/espace/scanner': typeof AuthenticatedEspaceScannerRoute
  '/_authenticated/pro/dossier': typeof AuthenticatedProDossierRoute
  '/_authenticated/pro/entreprise': typeof AuthenticatedProEntrepriseRoute
  '/_authenticated/pro/liens': typeof AuthenticatedProLiensRoute
  '/_authenticated/pro/parametres': typeof AuthenticatedProParametresRoute
  '/_authenticated/pro/personnalisation': typeof AuthenticatedProPersonnalisationRoute
  '/_authenticated/pro/profil': typeof AuthenticatedProProfilRoute
  '/_authenticated/pro/qr': typeof AuthenticatedProQrRoute
  '/_authenticated/pro/tarification': typeof AuthenticatedProTarificationRoute
  '/_authenticated/pro/vehicule': typeof AuthenticatedProVehiculeRoute
  '/_authenticated/pro/verification': typeof AuthenticatedProVerificationRoute
  '/_authenticated/support/$ticketId': typeof AuthenticatedSupportTicketIdRoute
  '/_authenticated/support/nouveau': typeof AuthenticatedSupportNouveauRoute
  '/api/public/push': typeof ApiPublicPushRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/espace/': typeof AuthenticatedEspaceIndexRoute
  '/_authenticated/pro/': typeof AuthenticatedProIndexRoute
  '/_authenticated/support/': typeof AuthenticatedSupportIndexRoute
  '/_authenticated/admin/chauffeurs/$driverId': typeof AuthenticatedAdminChauffeursDriverIdRoute
  '/_authenticated/admin/inscriptions/$driverId': typeof AuthenticatedAdminInscriptionsDriverIdRoute
  '/_authenticated/admin/support/$ticketId': typeof AuthenticatedAdminSupportTicketIdRoute
  '/_authenticated/admin/utilisateurs/$clientId': typeof AuthenticatedAdminUtilisateursClientIdRoute
  '/_authenticated/admin/chauffeurs/': typeof AuthenticatedAdminChauffeursIndexRoute
  '/_authenticated/admin/inscriptions/': typeof AuthenticatedAdminInscriptionsIndexRoute
  '/_authenticated/admin/support/': typeof AuthenticatedAdminSupportIndexRoute
  '/_authenticated/admin/utilisateurs/': typeof AuthenticatedAdminUtilisateursIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aide'
    | '/auth'
    | '/chauffeurs'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verification'
    | '/admin'
    | '/espace'
    | '/pro'
    | '/auth/callback'
    | '/auth/confirm'
    | '/chauffeur/$slug'
    | '/legal/$doc'
    | '/q/$slug'
    | '/admin/inscriptions'
    | '/admin/signalements'
    | '/admin/top10'
    | '/espace/chauffeurs'
    | '/espace/decouvrir'
    | '/espace/parametres'
    | '/espace/scanner'
    | '/pro/dossier'
    | '/pro/entreprise'
    | '/pro/liens'
    | '/pro/parametres'
    | '/pro/personnalisation'
    | '/pro/profil'
    | '/pro/qr'
    | '/pro/tarification'
    | '/pro/vehicule'
    | '/pro/verification'
    | '/support/$ticketId'
    | '/support/nouveau'
    | '/api/public/push'
    | '/admin/'
    | '/espace/'
    | '/pro/'
    | '/support/'
    | '/admin/chauffeurs/$driverId'
    | '/admin/inscriptions/$driverId'
    | '/admin/support/$ticketId'
    | '/admin/utilisateurs/$clientId'
    | '/admin/chauffeurs/'
    | '/admin/inscriptions/'
    | '/admin/support/'
    | '/admin/utilisateurs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aide'
    | '/auth'
    | '/chauffeurs'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verification'
    | '/auth/callback'
    | '/auth/confirm'
    | '/chauffeur/$slug'
    | '/legal/$doc'
    | '/q/$slug'
    | '/admin/signalements'
    | '/admin/top10'
    | '/espace/chauffeurs'
    | '/espace/decouvrir'
    | '/espace/parametres'
    | '/espace/scanner'
    | '/pro/dossier'
    | '/pro/entreprise'
    | '/pro/liens'
    | '/pro/parametres'
    | '/pro/personnalisation'
    | '/pro/profil'
    | '/pro/qr'
    | '/pro/tarification'
    | '/pro/vehicule'
    | '/pro/verification'
    | '/support/$ticketId'
    | '/support/nouveau'
    | '/api/public/push'
    | '/admin'
    | '/espace'
    | '/pro'
    | '/support'
    | '/admin/chauffeurs/$driverId'
    | '/admin/inscriptions/$driverId'
    | '/admin/support/$ticketId'
    | '/admin/utilisateurs/$clientId'
    | '/admin/chauffeurs'
    | '/admin/inscriptions'
    | '/admin/support'
    | '/admin/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/aide'
    | '/auth'
    | '/chauffeurs'
    | '/reset-password'
    | '/sitemap.xml'
    | '/verification'
    | '/_authenticated/admin'
    | '/_authenticated/espace'
    | '/_authenticated/pro'
    | '/auth_/callback'
    | '/auth_/confirm'
    | '/chauffeur/$slug'
    | '/legal/$doc'
    | '/q/$slug'
    | '/_authenticated/admin/inscriptions'
    | '/_authenticated/admin/signalements'
    | '/_authenticated/admin/top10'
    | '/_authenticated/espace/chauffeurs'
    | '/_authenticated/espace/decouvrir'
    | '/_authenticated/espace/parametres'
    | '/_authenticated/espace/scanner'
    | '/_authenticated/pro/dossier'
    | '/_authenticated/pro/entreprise'
    | '/_authenticated/pro/liens'
    | '/_authenticated/pro/parametres'
    | '/_authenticated/pro/personnalisation'
    | '/_authenticated/pro/profil'
    | '/_authenticated/pro/qr'
    | '/_authenticated/pro/tarification'
    | '/_authenticated/pro/vehicule'
    | '/_authenticated/pro/verification'
    | '/_authenticated/support/$ticketId'
    | '/_authenticated/support/nouveau'
    | '/api/public/push'
    | '/_authenticated/admin/'
    | '/_authenticated/espace/'
    | '/_authenticated/pro/'
    | '/_authenticated/support/'
    | '/_authenticated/admin/chauffeurs/$driverId'
    | '/_authenticated/admin/inscriptions/$driverId'
    | '/_authenticated/admin/support/$ticketId'
    | '/_authenticated/admin/utilisateurs/$clientId'
    | '/_authenticated/admin/chauffeurs/'
    | '/_authenticated/admin/inscriptions/'
    | '/_authenticated/admin/support/'
    | '/_authenticated/admin/utilisateurs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AideRoute: typeof AideRoute
  AuthRoute: typeof AuthRoute
  ChauffeursRoute: typeof ChauffeursRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VerificationRoute: typeof VerificationRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  ChauffeurSlugRoute: typeof ChauffeurSlugRoute
  LegalDocRoute: typeof LegalDocRoute
  QSlugRoute: typeof QSlugRoute
  ApiPublicPushRoute: typeof ApiPublicPushRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeurs': {
      id: '/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/chauffeurs'
      preLoaderRoute: typeof ChauffeursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verification': {
      id: '/verification'
      path: '/verification'
      fullPath: '/verification'
      preLoaderRoute: typeof VerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/espace': {
      id: '/_authenticated/espace'
      path: '/espace'
      fullPath: '/espace'
      preLoaderRoute: typeof AuthenticatedEspaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pro': {
      id: '/_authenticated/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof AuthenticatedProRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth_/confirm': {
      id: '/auth_/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chauffeur/$slug': {
      id: '/chauffeur/$slug'
      path: '/chauffeur/$slug'
      fullPath: '/chauffeur/$slug'
      preLoaderRoute: typeof ChauffeurSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$doc': {
      id: '/legal/$doc'
      path: '/legal/$doc'
      fullPath: '/legal/$doc'
      preLoaderRoute: typeof LegalDocRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inscriptions': {
      id: '/_authenticated/admin/inscriptions'
      path: '/inscriptions'
      fullPath: '/admin/inscriptions'
      preLoaderRoute: typeof AuthenticatedAdminInscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/signalements': {
      id: '/_authenticated/admin/signalements'
      path: '/signalements'
      fullPath: '/admin/signalements'
      preLoaderRoute: typeof AuthenticatedAdminSignalementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/top10': {
      id: '/_authenticated/admin/top10'
      path: '/top10'
      fullPath: '/admin/top10'
      preLoaderRoute: typeof AuthenticatedAdminTop10RouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/espace/': {
      id: '/_authenticated/espace/'
      path: '/'
      fullPath: '/espace/'
      preLoaderRoute: typeof AuthenticatedEspaceIndexRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/chauffeurs': {
      id: '/_authenticated/espace/chauffeurs'
      path: '/chauffeurs'
      fullPath: '/espace/chauffeurs'
      preLoaderRoute: typeof AuthenticatedEspaceChauffeursRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/decouvrir': {
      id: '/_authenticated/espace/decouvrir'
      path: '/decouvrir'
      fullPath: '/espace/decouvrir'
      preLoaderRoute: typeof AuthenticatedEspaceDecouvrirRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/parametres': {
      id: '/_authenticated/espace/parametres'
      path: '/parametres'
      fullPath: '/espace/parametres'
      preLoaderRoute: typeof AuthenticatedEspaceParametresRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/espace/scanner': {
      id: '/_authenticated/espace/scanner'
      path: '/scanner'
      fullPath: '/espace/scanner'
      preLoaderRoute: typeof AuthenticatedEspaceScannerRouteImport
      parentRoute: typeof AuthenticatedEspaceRoute
    }
    '/_authenticated/pro/': {
      id: '/_authenticated/pro/'
      path: '/'
      fullPath: '/pro/'
      preLoaderRoute: typeof AuthenticatedProIndexRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/dossier': {
      id: '/_authenticated/pro/dossier'
      path: '/dossier'
      fullPath: '/pro/dossier'
      preLoaderRoute: typeof AuthenticatedProDossierRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/entreprise': {
      id: '/_authenticated/pro/entreprise'
      path: '/entreprise'
      fullPath: '/pro/entreprise'
      preLoaderRoute: typeof AuthenticatedProEntrepriseRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/liens': {
      id: '/_authenticated/pro/liens'
      path: '/liens'
      fullPath: '/pro/liens'
      preLoaderRoute: typeof AuthenticatedProLiensRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/parametres': {
      id: '/_authenticated/pro/parametres'
      path: '/parametres'
      fullPath: '/pro/parametres'
      preLoaderRoute: typeof AuthenticatedProParametresRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/personnalisation': {
      id: '/_authenticated/pro/personnalisation'
      path: '/personnalisation'
      fullPath: '/pro/personnalisation'
      preLoaderRoute: typeof AuthenticatedProPersonnalisationRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/profil': {
      id: '/_authenticated/pro/profil'
      path: '/profil'
      fullPath: '/pro/profil'
      preLoaderRoute: typeof AuthenticatedProProfilRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/qr': {
      id: '/_authenticated/pro/qr'
      path: '/qr'
      fullPath: '/pro/qr'
      preLoaderRoute: typeof AuthenticatedProQrRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/tarification': {
      id: '/_authenticated/pro/tarification'
      path: '/tarification'
      fullPath: '/pro/tarification'
      preLoaderRoute: typeof AuthenticatedProTarificationRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/vehicule': {
      id: '/_authenticated/pro/vehicule'
      path: '/vehicule'
      fullPath: '/pro/vehicule'
      preLoaderRoute: typeof AuthenticatedProVehiculeRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/pro/verification': {
      id: '/_authenticated/pro/verification'
      path: '/verification'
      fullPath: '/pro/verification'
      preLoaderRoute: typeof AuthenticatedProVerificationRouteImport
      parentRoute: typeof AuthenticatedProRoute
    }
    '/_authenticated/support/': {
      id: '/_authenticated/support/'
      path: '/support'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthenticatedSupportIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/$ticketId': {
      id: '/_authenticated/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AuthenticatedSupportTicketIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support/nouveau': {
      id: '/_authenticated/support/nouveau'
      path: '/support/nouveau'
      fullPath: '/support/nouveau'
      preLoaderRoute: typeof AuthenticatedSupportNouveauRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/push': {
      id: '/api/public/push'
      path: '/api/public/push'
      fullPath: '/api/public/push'
      preLoaderRoute: typeof ApiPublicPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/chauffeurs/': {
      id: '/_authenticated/admin/chauffeurs/'
      path: '/chauffeurs'
      fullPath: '/admin/chauffeurs/'
      preLoaderRoute: typeof AuthenticatedAdminChauffeursIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/chauffeurs/$driverId': {
      id: '/_authenticated/admin/chauffeurs/$driverId'
      path: '/chauffeurs/$driverId'
      fullPath: '/admin/chauffeurs/$driverId'
      preLoaderRoute: typeof AuthenticatedAdminChauffeursDriverIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/inscriptions/': {
      id: '/_authenticated/admin/inscriptions/'
      path: '/'
      fullPath: '/admin/inscriptions/'
      preLoaderRoute: typeof AuthenticatedAdminInscriptionsIndexRouteImport
      parentRoute: typeof AuthenticatedAdminInscriptionsRoute
    }
    '/_authenticated/admin/inscriptions/$driverId': {
      id: '/_authenticated/admin/inscriptions/$driverId'
      path: '/$driverId'
      fullPath: '/admin/inscriptions/$driverId'
      preLoaderRoute: typeof AuthenticatedAdminInscriptionsDriverIdRouteImport
      parentRoute: typeof AuthenticatedAdminInscriptionsRoute
    }
    '/_authenticated/admin/support/': {
      id: '/_authenticated/admin/support/'
      path: '/support'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AuthenticatedAdminSupportIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support/$ticketId': {
      id: '/_authenticated/admin/support/$ticketId'
      path: '/support/$ticketId'
      fullPath: '/admin/support/$ticketId'
      preLoaderRoute: typeof AuthenticatedAdminSupportTicketIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs/': {
      id: '/_authenticated/admin/utilisateurs/'
      path: '/utilisateurs'
      fullPath: '/admin/utilisateurs/'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/utilisateurs/$clientId': {
      id: '/_authenticated/admin/utilisateurs/$clientId'
      path: '/utilisateurs/$clientId'
      fullPath: '/admin/utilisateurs/$clientId'
      preLoaderRoute: typeof AuthenticatedAdminUtilisateursClientIdRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminInscriptionsRouteChildren {
  AuthenticatedAdminInscriptionsDriverIdRoute: typeof AuthenticatedAdminInscriptionsDriverIdRoute
  AuthenticatedAdminInscriptionsIndexRoute: typeof AuthenticatedAdminInscriptionsIndexRoute
}

const AuthenticatedAdminInscriptionsRouteChildren: AuthenticatedAdminInscriptionsRouteChildren =
  {
    AuthenticatedAdminInscriptionsDriverIdRoute:
      AuthenticatedAdminInscriptionsDriverIdRoute,
    AuthenticatedAdminInscriptionsIndexRoute:
      AuthenticatedAdminInscriptionsIndexRoute,
  }

const AuthenticatedAdminInscriptionsRouteWithChildren =
  AuthenticatedAdminInscriptionsRoute._addFileChildren(
    AuthenticatedAdminInscriptionsRouteChildren,
  )

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminInscriptionsRoute: typeof AuthenticatedAdminInscriptionsRouteWithChildren
  AuthenticatedAdminSignalementsRoute: typeof AuthenticatedAdminSignalementsRoute
  AuthenticatedAdminTop10Route: typeof AuthenticatedAdminTop10Route
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminChauffeursDriverIdRoute: typeof AuthenticatedAdminChauffeursDriverIdRoute
  AuthenticatedAdminSupportTicketIdRoute: typeof AuthenticatedAdminSupportTicketIdRoute
  AuthenticatedAdminUtilisateursClientIdRoute: typeof AuthenticatedAdminUtilisateursClientIdRoute
  AuthenticatedAdminChauffeursIndexRoute: typeof AuthenticatedAdminChauffeursIndexRoute
  AuthenticatedAdminSupportIndexRoute: typeof AuthenticatedAdminSupportIndexRoute
  AuthenticatedAdminUtilisateursIndexRoute: typeof AuthenticatedAdminUtilisateursIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminInscriptionsRoute:
    AuthenticatedAdminInscriptionsRouteWithChildren,
  AuthenticatedAdminSignalementsRoute: AuthenticatedAdminSignalementsRoute,
  AuthenticatedAdminTop10Route: AuthenticatedAdminTop10Route,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminChauffeursDriverIdRoute:
    AuthenticatedAdminChauffeursDriverIdRoute,
  AuthenticatedAdminSupportTicketIdRoute:
    AuthenticatedAdminSupportTicketIdRoute,
  AuthenticatedAdminUtilisateursClientIdRoute:
    AuthenticatedAdminUtilisateursClientIdRoute,
  AuthenticatedAdminChauffeursIndexRoute:
    AuthenticatedAdminChauffeursIndexRoute,
  AuthenticatedAdminSupportIndexRoute: AuthenticatedAdminSupportIndexRoute,
  AuthenticatedAdminUtilisateursIndexRoute:
    AuthenticatedAdminUtilisateursIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedEspaceRouteChildren {
  AuthenticatedEspaceChauffeursRoute: typeof AuthenticatedEspaceChauffeursRoute
  AuthenticatedEspaceDecouvrirRoute: typeof AuthenticatedEspaceDecouvrirRoute
  AuthenticatedEspaceParametresRoute: typeof AuthenticatedEspaceParametresRoute
  AuthenticatedEspaceScannerRoute: typeof AuthenticatedEspaceScannerRoute
  AuthenticatedEspaceIndexRoute: typeof AuthenticatedEspaceIndexRoute
}

const AuthenticatedEspaceRouteChildren: AuthenticatedEspaceRouteChildren = {
  AuthenticatedEspaceChauffeursRoute: AuthenticatedEspaceChauffeursRoute,
  AuthenticatedEspaceDecouvrirRoute: AuthenticatedEspaceDecouvrirRoute,
  AuthenticatedEspaceParametresRoute: AuthenticatedEspaceParametresRoute,
  AuthenticatedEspaceScannerRoute: AuthenticatedEspaceScannerRoute,
  AuthenticatedEspaceIndexRoute: AuthenticatedEspaceIndexRoute,
}

const AuthenticatedEspaceRouteWithChildren =
  AuthenticatedEspaceRoute._addFileChildren(AuthenticatedEspaceRouteChildren)

interface AuthenticatedProRouteChildren {
  AuthenticatedProDossierRoute: typeof AuthenticatedProDossierRoute
  AuthenticatedProEntrepriseRoute: typeof AuthenticatedProEntrepriseRoute
  AuthenticatedProLiensRoute: typeof AuthenticatedProLiensRoute
  AuthenticatedProParametresRoute: typeof AuthenticatedProParametresRoute
  AuthenticatedProPersonnalisationRoute: typeof AuthenticatedProPersonnalisationRoute
  AuthenticatedProProfilRoute: typeof AuthenticatedProProfilRoute
  AuthenticatedProQrRoute: typeof AuthenticatedProQrRoute
  AuthenticatedProTarificationRoute: typeof AuthenticatedProTarificationRoute
  AuthenticatedProVehiculeRoute: typeof AuthenticatedProVehiculeRoute
  AuthenticatedProVerificationRoute: typeof AuthenticatedProVerificationRoute
  AuthenticatedProIndexRoute: typeof AuthenticatedProIndexRoute
}

const AuthenticatedProRouteChildren: AuthenticatedProRouteChildren = {
  AuthenticatedProDossierRoute: AuthenticatedProDossierRoute,
  AuthenticatedProEntrepriseRoute: AuthenticatedProEntrepriseRoute,
  AuthenticatedProLiensRoute: AuthenticatedProLiensRoute,
  AuthenticatedProParametresRoute: AuthenticatedProParametresRoute,
  AuthenticatedProPersonnalisationRoute: AuthenticatedProPersonnalisationRoute,
  AuthenticatedProProfilRoute: AuthenticatedProProfilRoute,
  AuthenticatedProQrRoute: AuthenticatedProQrRoute,
  AuthenticatedProTarificationRoute: AuthenticatedProTarificationRoute,
  AuthenticatedProVehiculeRoute: AuthenticatedProVehiculeRoute,
  AuthenticatedProVerificationRoute: AuthenticatedProVerificationRoute,
  AuthenticatedProIndexRoute: AuthenticatedProIndexRoute,
}

const AuthenticatedProRouteWithChildren =
  AuthenticatedProRoute._addFileChildren(AuthenticatedProRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedEspaceRoute: typeof AuthenticatedEspaceRouteWithChildren
  AuthenticatedProRoute: typeof AuthenticatedProRouteWithChildren
  AuthenticatedSupportTicketIdRoute: typeof AuthenticatedSupportTicketIdRoute
  AuthenticatedSupportNouveauRoute: typeof AuthenticatedSupportNouveauRoute
  AuthenticatedSupportIndexRoute: typeof AuthenticatedSupportIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedEspaceRoute: AuthenticatedEspaceRouteWithChildren,
  AuthenticatedProRoute: AuthenticatedProRouteWithChildren,
  AuthenticatedSupportTicketIdRoute: AuthenticatedSupportTicketIdRoute,
  AuthenticatedSupportNouveauRoute: AuthenticatedSupportNouveauRoute,
  AuthenticatedSupportIndexRoute: AuthenticatedSupportIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AideRoute: AideRoute,
  AuthRoute: AuthRoute,
  ChauffeursRoute: ChauffeursRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VerificationRoute: VerificationRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  ChauffeurSlugRoute: ChauffeurSlugRoute,
  LegalDocRoute: LegalDocRoute,
  QSlugRoute: QSlugRoute,
  ApiPublicPushRoute: ApiPublicPushRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
