-- ============ SUPPORT SAV ============
CREATE TABLE public.support_tickets (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_number bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) UNIQUE,
  user_id uuid NOT NULL,
  user_kind text NOT NULL DEFAULT 'client',
  category text NOT NULL,
  subject text NOT NULL,
  status text NOT NULL DEFAULT 'new',
  origin_path text,
  assigned_admin uuid,
  last_message_at timestamptz NOT NULL DEFAULT now(),
  last_admin_reply_at timestamptz,
  user_unread boolean NOT NULL DEFAULT false,
  admin_unread boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT support_tickets_status_check CHECK (status IN ('new','in_progress','waiting_user','resolved','closed')),
  CONSTRAINT support_tickets_kind_check CHECK (user_kind IN ('client','driver'))
);

CREATE INDEX support_tickets_user_idx ON public.support_tickets(user_id, created_at DESC);
CREATE INDEX support_tickets_status_idx ON public.support_tickets(status, last_message_at DESC);

GRANT SELECT, INSERT, UPDATE ON public.support_tickets TO authenticated;
GRANT ALL ON public.support_tickets TO service_role;
ALTER TABLE public.support_tickets ENABLE ROW LEVEL SECURITY;

CREATE POLICY "tickets_select_own_or_admin" ON public.support_tickets
  FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.is_admin(auth.uid()));

CREATE POLICY "tickets_insert_own" ON public.support_tickets
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());

CREATE POLICY "tickets_update_admin" ON public.support_tickets
  FOR UPDATE TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

CREATE TABLE public.support_messages (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id uuid NOT NULL REFERENCES public.support_tickets(id) ON DELETE CASCADE,
  author_id uuid,
  author_kind text NOT NULL,
  body text NOT NULL,
  attachment_path text,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT support_messages_author_kind_check CHECK (author_kind IN ('user','admin'))
);

CREATE INDEX support_messages_ticket_idx ON public.support_messages(ticket_id, created_at);

GRANT SELECT, INSERT ON public.support_messages TO authenticated;
GRANT ALL ON public.support_messages TO service_role;
ALTER TABLE public.support_messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "support_messages_select" ON public.support_messages
  FOR SELECT TO authenticated
  USING (
    public.is_admin(auth.uid())
    OR EXISTS (SELECT 1 FROM public.support_tickets t WHERE t.id = ticket_id AND t.user_id = auth.uid())
  );

CREATE POLICY "support_messages_insert" ON public.support_messages
  FOR INSERT TO authenticated
  WITH CHECK (
    author_id = auth.uid()
    AND (
      (author_kind = 'admin' AND public.is_admin(auth.uid()))
      OR (
        author_kind = 'user'
        AND EXISTS (
          SELECT 1 FROM public.support_tickets t
          WHERE t.id = ticket_id AND t.user_id = auth.uid() AND t.status <> 'closed'
        )
      )
    )
  );

-- Synchronisation du ticket à chaque message
CREATE OR REPLACE FUNCTION public.support_message_touch_ticket()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.author_kind = 'admin' THEN
    UPDATE public.support_tickets
      SET last_message_at = now(),
          updated_at = now(),
          last_admin_reply_at = now(),
          user_unread = true,
          admin_unread = false,
          assigned_admin = COALESCE(assigned_admin, NEW.author_id),
          status = CASE WHEN status IN ('new','in_progress') THEN 'waiting_user' ELSE status END
      WHERE id = NEW.ticket_id;
  ELSE
    UPDATE public.support_tickets
      SET last_message_at = now(),
          updated_at = now(),
          admin_unread = true,
          user_unread = false,
          status = CASE WHEN status IN ('waiting_user','resolved') THEN 'in_progress' ELSE status END
      WHERE id = NEW.ticket_id;
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER support_message_touch_ticket
AFTER INSERT ON public.support_messages
FOR EACH ROW EXECUTE FUNCTION public.support_message_touch_ticket();

CREATE TRIGGER support_tickets_updated_at
BEFORE UPDATE ON public.support_tickets
FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();

-- ============ TARIFS : correction administrative ============
CREATE POLICY "driver_tariffs_admin_write" ON public.driver_tariffs
  FOR ALL TO authenticated
  USING (public.is_admin(auth.uid()))
  WITH CHECK (public.is_admin(auth.uid()));

-- ============ HISTORIQUE ADMIN ============
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS support_ticket_id uuid;
ALTER TABLE public.audit_logs ADD COLUMN IF NOT EXISTS target_user_id uuid;
CREATE INDEX IF NOT EXISTS audit_logs_target_idx ON public.audit_logs(target_user_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.admin_log_change(
  _target_user_id uuid,
  _action text,
  _field text,
  _old_value jsonb,
  _new_value jsonb,
  _reason text DEFAULT NULL,
  _ticket_id uuid DEFAULT NULL
)
RETURNS uuid
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _id uuid;
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  INSERT INTO public.audit_logs (actor_id, action, resource, resource_id, target_user_id, old_value, new_value, reason, support_ticket_id)
  VALUES (auth.uid(), _action, _field, _target_user_id, _target_user_id, _old_value, _new_value, _reason, _ticket_id)
  RETURNING id INTO _id;
  RETURN _id;
END;
$$;

REVOKE ALL ON FUNCTION public.admin_log_change(uuid, text, text, jsonb, jsonb, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_log_change(uuid, text, text, jsonb, jsonb, text, uuid) TO authenticated;

-- Correction administrative du sexe (SAV) : contourne le quota, réaligne Woman for Woman
CREATE OR REPLACE FUNCTION public.admin_set_user_gender(_user_id uuid, _gender text, _ticket_id uuid DEFAULT NULL)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  _old text;
BEGIN
  IF NOT public.is_admin(auth.uid()) THEN
    RAISE EXCEPTION 'forbidden';
  END IF;
  IF _gender IS NULL OR _gender NOT IN ('female','male','undisclosed') THEN
    RAISE EXCEPTION 'invalid_gender';
  END IF;

  SELECT gender INTO _old FROM public.profiles WHERE id = _user_id FOR UPDATE;
  UPDATE public.profiles SET gender = _gender WHERE id = _user_id;

  UPDATE public.driver_profiles
    SET gender = _gender,
        booking_theme = CASE WHEN _gender <> 'female' AND booking_theme = 'women_for_women'
                             THEN 'relink_classic' ELSE booking_theme END,
        woman_for_woman = CASE WHEN _gender <> 'female' THEN false ELSE woman_for_woman END,
        women_for_women_eligible = CASE WHEN _gender <> 'female' THEN false ELSE women_for_women_eligible END
    WHERE user_id = _user_id;

  PERFORM public.admin_log_change(_user_id, 'admin.gender_update', 'gender',
    to_jsonb(_old), to_jsonb(_gender), 'Correction SAV', _ticket_id);

  RETURN jsonb_build_object('gender', _gender, 'previous', _old);
END;
$$;

REVOKE ALL ON FUNCTION public.admin_set_user_gender(uuid, text, uuid) FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.admin_set_user_gender(uuid, text, uuid) TO authenticated;